# Configuração do yamllint
extends: default

rules:
  # Configuração de linha
  line-length:
    max: 120
    level: warning

  # Configuração de comentários
  comments:
    min-spaces-from-content: 1

  # Configuração de indentação
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false

  # Configuração de documentos
  document-start: disable
  document-end: disable

  # Configuração de colchetes
  brackets:
    forbid-implicit-octal: true

  # Ignorar alguns arquivos
ignore: |
  .venv/
  build/
  dist/
  *.egg-info/
  .tox/
  .mypy_cache/
  .pytest_cache/ 