# Configuração DEBUG para teste rápido do sistema em inglês
name: "vits2_english_debug"

# === Configuração do Modelo ===
model:
  name: "VITS2"
  text_encoder_hidden_dim: 128 # Reduzido de 192
  latent_dim: 128 # Reduzido de 192
  mel_channels: 80
  n_speakers: 52 # Ajustar conforme número de falantes no dataset
  speaker_embedding_dim: 256 # Deve ser igual ao generator_initial_channels

  # Configurações específicas para inglês
  text_processor: "english"

  # Configurações do generator (reduzidas mas compatíveis)
  generator_initial_channels: 256 # Reduzido de 512
  gin_channels: 256 # Reduzido de 512, deve ser igual ao speaker_embedding_dim
  decoder_hidden_dim: 256 # Deve ser igual ao generator_initial_channels

  # Configurações de inferência
  inference_only: false

# === Configuração de Treinamento DEBUG ===
training:
  max_epochs: 3 # Apenas 3 épocas para teste
  batch_size: 2 # Muito pequeno para debug
  learning_rate: 1e-4
  weight_decay: 1e-6
  beta1: 0.8
  beta2: 0.99
  use_amp: true
  gradient_clip_val: 1000.0
  accumulate_grad_batches: 1

  # Logging frequente para debug
  log_every_n_steps: 5
  val_check_interval: 0.5 # Validação 2x por época
  save_every_n_epochs: 1 # Salvar toda época

  # Loss weights simples
  lambda_mel: 45.0
  lambda_kl: 1.0
  lambda_gen: 1.0
  lambda_disc: 1.0

# === Configuração de Logging ===
logging:
  log_dir: "logs"
  experiment_name: "vits2_english_debug"

  # Checkpoints para debug
  checkpoint:
    monitor: "val_loss"
    mode: "min"
    save_top_k: 1
    save_last: true
    dirpath: "checkpoints/debug"
    filename: "vits2_debug-{epoch:02d}-{val_loss:.2f}"

  # Early stopping para debug (desabilitado)
  early_stopping:
    monitor: "epoch/val_loss_total"
    mode: "min"
    patience: 10
    min_delta: 0.001

  # TensorBoard simplificado
  tensorboard:
    save_dir: "logs/tensorboard"
    name: "vits2_debug"
    log_graph: false
    log_hparams: true

# === Configuração de Dados DEBUG ===
data:
  data_dir: "data/generated/Dataset-Unificado"
  metadata_file: "data/generated/Dataset-Unificado/metadata.csv"
  sample_rate: 22050
  n_fft: 1024
  hop_length: 256
  n_mels: 80
  max_wav_value: 32768.0

  # LIMITE PARA DEBUG - apenas 100 amostras
  max_samples_debug: 100
  cache_preprocessed: true

  # Data loading para debug
  num_workers: 2 # Reduzido
  pin_memory: true
  persistent_workers: false # Para debug

# === Configuração Dataset ===
dataset_config:
  locale_column: "locale"
  expected_locale: "en"
  text_column: "text_normalized"
  audio_path_column: "audio_path"
  speaker_column: "speaker_id"
  duration_column: "duration"

# === Processamento de Texto INGLÊS ===
text_processor:
  use_phonemes: true
  phoneme_backend: "espeak"
  phoneme_language: "en-us"
  vocab_size: 256 # Reduzido para debug

  # Cache para acelerar
  cache_phonemes: true
  clean_text: true

  # Configuração específica inglês
  language: "en-us"
  class: "valetts.data.preprocessing.text_en.EnglishTextPreprocessor"

# === Monitor LLM (Opcional) ===
llm_monitor:
  enabled: true
  provider: "openrouter"
  model: "anthropic/claude-3.5-haiku"
  monitor_every_epochs: 1 # A cada época para debug
  auto_adjust: false # Desabilitado para debug
  send_metrics: false

  # Configuração de debug
  max_history: 5
  temperature: 0.1

# === Configuração de Hardware ===
hardware:
  accelerator: "gpu"
  devices: 1
  precision: "16-mixed"
  strategy: "auto"
  sync_batchnorm: false # Desabilitado para debug
  benchmark: false # Desabilitado para debug
  deterministic: false

# === Configuração de Validação ===
validation:
  val_check_interval: 1.0
  limit_val_batches: 1.0
  num_sanity_val_steps: 2 # Reduzido para debug

  # Geração de amostras para debug
  generate_samples: true
  sample_every_n_epochs: 1 # A cada época para debug
