# === CONFIGURAÇÃO OTIMIZADA VITS2 INGLÊS PARA A100 ===
# Performance máxima: A100 40GB VRAM
# Dataset: 22.910 amostras em inglês
# Objetivo: 5-8 it/s para treinamento eficiente

# === Configuração do Modelo (Otimizada A100) ===
model:
  # Informações básicas do modelo
  name: "VITS2"

  # Parâmetros de áudio
  mel_channels: 80
  hop_length: 256

  # Configuração de speakers
  n_speakers: 52
  speaker_embedding_dim: 1024 # Aumentado para A100

  # Text encoder configuration
  text_encoder_hidden_dim: 512 # Aumentado para A100
  text_hidden_dim: 512
  text_encoder_layers: 6
  text_encoder_attention_heads: 2
  text_encoder_filter_size: 768
  text_filter_channels: 768
  text_num_heads: 2
  text_num_layers: 6
  text_kernel_size: 3
  text_dropout: 0.1
  max_text_length: 1000

  # Flow configuration (otimizado para A100)
  latent_dim: 512 # Aumentado para A100
  flow_gin_channels: 1024 # Parâmetro correto para flow
  flow_flows: 4
  flow_kernel_size: 5
  flow_base_dilation: 1
  flow_num_layers: 4
  flow_hidden_channels: 512 # Aumentado para A100
  flow_dilation_rate: 1
  n_flow_blocks: 4
  n_flow_layers: 4

  # Generator configuration (A100 otimizado)
  generator_initial_channels: 1024 # Aumentado para A100
  decoder_hidden_dim: 1024 # Igual ao generator_initial_channels
  generator_resblock_type: "1"
  generator_resblock_dilation_sizes:
    - [1, 3, 5]
    - [1, 3, 5]
    - [1, 3, 5]
  generator_resblock_kernel_sizes: [3, 7, 11]
  upsample_rates: [8, 8, 2, 2]
  upsample_kernel_sizes: [16, 16, 4, 4]
  generator_upsample_rates: [8, 8, 2, 2]
  generator_upsample_initial_channel: 1024 # Aumentado para A100
  generator_upsample_kernel_sizes: [16, 16, 4, 4]

  # Loss weights (balanceados para inglês)
  lambda_adv: 1.0
  lambda_mel: 45.0
  lambda_feat: 2.0
  lambda_dur: 1.0
  lambda_kl: 1.0
  adversarial_loss_weight: 1.0
  feature_matching_loss_weight: 2.0
  mel_loss_weight: 45.0
  duration_loss_weight: 1.0
  kl_loss_weight: 1.0

  # Training flags
  use_mel_loss: true
  use_kl_loss: true
  use_duration_loss: true
  use_feature_matching_loss: true
  inference_only: false

  # Inference configuration
  inference_noise_scale: 0.667
  inference_noise_scale_w: 0.8
  inference_length_scale: 1.0

# === Configuração de Treinamento (A100 Otimizado) ===
training:
  # Parâmetros otimizados para A100 40GB
  learning_rate: 2.0e-4
  batch_size: 32 # Otimizado para A100 40GB
  max_epochs: 200
  accumulate_grad_batches: 1 # A100 não precisa de acumulação
  max_grad_norm: 1.0

  # Loss weights balanceados para inglês
  mel_loss_weight: 45.0
  kl_loss_weight: 1.0
  adv_loss_weight: 1.0
  fm_loss_weight: 2.0
  duration_loss_weight: 1.0

  # Otimização avançada para A100
  use_amp: true # Mixed precision essential
  gradient_clip_val: 1.0
  discriminator_update_frequency: 1

  # Scheduler otimizado para A100
  scheduler:
    name: "ReduceLROnPlateau"
    mode: "min"
    factor: 0.5
    patience: 15
    min_lr: 1.0e-6

# === Configuração de Dados (Inglês Específico) ===
data:
  dataset_format: "valetts"
  data_dir: "/content/dataset/Dataset-Unificado"
  metadata_file: "/content/dataset/Dataset-Unificado/metadata.csv"

  # Configuração de idioma inglês
  language: "en" # Usar coluna locale = "en"
  locale_column: "locale"

  # Configuração do processador de texto para inglês
  text_processor:
    use_phonemes: true
    normalize_numbers: true
    normalize_whitespace: true
    lowercase: true
    language: "en-us"

  # Preprocessing de áudio
  sample_rate: 22050
  n_mels: 80
  n_fft: 1024
  hop_length: 256
  win_length: 1024

  # Data loading otimizado para A100
  num_workers: 12 # Aumentado para A100
  pin_memory: true
  persistent_workers: true
  prefetch_factor: 4 # Otimização para A100

  # Augmentation para inglês
  use_augmentation: true
  volume_range: [0.9, 1.1]
  pitch_range: [-1, 1]

  # Filtros de qualidade para inglês
  min_duration: 0.5
  max_duration: 15.0
  min_text_length: 10
  max_text_length: 300

# === Configuração de Logging ===
logging:
  log_dir: "logs"
  experiment_name: "vits2_english_a100"

  # SISTEMA HÍBRIDO DE CHECKPOINTS
  checkpoint:
    # Checkpoints principais (2 últimos - se sobrescrevem)
    dirpath: "checkpoints/vits2_english_a100"
    filename: "vits2_en_a100-{epoch:03d}-{epoch/val_loss_total:.3f}"
    monitor: "epoch/val_loss_total"
    mode: "min"
    save_top_k: 2 # Apenas 2 checkpoints recentes
    save_last: true
    every_n_epochs: 1 # Salvar a cada época
    auto_insert_metric_name: false
    save_on_train_epoch_end: true

  # Checkpoints de backup (a cada 10 épocas - permanentes)
  checkpoint_backup:
    enabled: true
    dirpath: "checkpoints/vits2_english_a100/backup"
    filename: "vits2_en_a100_backup-{epoch:03d}-{epoch/val_loss_total:.3f}"
    every_n_epochs: 10 # Backup a cada 10 épocas
    save_top_k: -1 # Salvar todos os backups (nunca sobrescrever)
    monitor: "epoch/val_loss_total"
    mode: "min"

  early_stopping:
    monitor: "epoch/val_loss_total"
    mode: "min"
    patience: 30
    min_delta: 0.001

  tensorboard:
    save_dir: "logs/tensorboard"
    name: "vits2_english_a100"

# === Configuração de Hardware (A100 Específico) ===
hardware:
  accelerator: "gpu"
  devices: 1
  precision: "16-mixed" # Essential para A100
  strategy: "auto"
  sync_batchnorm: true
  benchmark: true # Otimização para A100
  deterministic: false # Performance over determinism

# === Configuração de Validação ===
validation:
  val_check_interval: 1.0
  generate_samples: true
  sample_every_n_epochs: 1 # Gerar amostras a cada época
  limit_val_batches: 1.0
  num_sanity_val_steps: 2

# === Configuração do Dataset Inglês ===
dataset_config:
  # Mapeamento de colunas correto
  audio_column: "audio_path"
  text_column: "text_normalized"
  speaker_column: "speaker_id"
  duration_column: "duration"
  locale_column: "locale"

  # Validação específica para inglês
  expected_locale: "en" # Valor na coluna locale
  validate_files: true
  cache_preprocessing: true

  # Filtros para dataset inglês
  required_columns: ["audio_path", "text_normalized", "speaker_id", "locale"]
  validate_phonemes: true

# === Configurações de Processamento Específicas ===
preprocessing:
  # Text normalization para inglês
  expand_abbreviations: true
  normalize_numbers: true
  convert_ordinals: true
  expand_contractions: true

  # Phoneme processing
  use_phonemes: true
  phoneme_separator: " "
  handle_oov_words: true

  # Audio processing
  normalize_audio: true
  trim_silence: true
  target_db: -23.0

# === Monitor LLM (Opcional) ===
llm_monitor:
  enabled: false # Desabilitado para máxima performance

# === Configurações de Performance A100 ===
performance:
  # Otimizações específicas para A100
  use_tensor_cores: true
  optimized_attention: true
  memory_efficient: false # A100 tem VRAM suficiente
  gradient_checkpointing: false # Desnecessário com 40GB

  # Batch size dinâmico baseado na VRAM
  adaptive_batch_size: true
  max_batch_size: 48 # Limite seguro para A100
  min_batch_size: 24 # Mínimo eficiente

  # Compilação do modelo (PyTorch 2.0+)
  compile_model: true
  compile_mode: "default"

# === Configuração de Amostras de Áudio ===
audio_sampling:
  enabled: true
  sample_every_n_epochs: 1 # Gerar amostras a cada época
  num_samples: 3 # 3 amostras por checkpoint
  max_length: 10.0 # Máximo 10 segundos
  sample_rate: 22050
  save_dir: "samples"
  speakers_to_sample: [0, 1, 2] # Primeiros 3 speakers
